// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: analizer.proto

package analyzer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Bpm           int32                  `protobuf:"varint,2,opt,name=bpm,proto3" json:"bpm,omitempty"`
	Timestamp     string                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserData) Reset() {
	*x = UserData{}
	mi := &file_analizer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserData) ProtoMessage() {}

func (x *UserData) ProtoReflect() protoreflect.Message {
	mi := &file_analizer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserData.ProtoReflect.Descriptor instead.
func (*UserData) Descriptor() ([]byte, []int) {
	return file_analizer_proto_rawDescGZIP(), []int{0}
}

func (x *UserData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserData) GetBpm() int32 {
	if x != nil {
		return x.Bpm
	}
	return 0
}

func (x *UserData) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type InsertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertResponse) Reset() {
	*x = InsertResponse{}
	mi := &file_analizer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertResponse) ProtoMessage() {}

func (x *InsertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analizer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertResponse.ProtoReflect.Descriptor instead.
func (*InsertResponse) Descriptor() ([]byte, []int) {
	return file_analizer_proto_rawDescGZIP(), []int{1}
}

func (x *InsertResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *InsertResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_analizer_proto protoreflect.FileDescriptor

const file_analizer_proto_rawDesc = "" +
	"\n" +
	"\x0eanalizer.proto\x12\x04user\"N\n" +
	"\bUserData\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03bpm\x18\x02 \x01(\x05R\x03bpm\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp\":\n" +
	"\x0eInsertResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2E\n" +
	"\vUserService\x126\n" +
	"\x0eInsertUserData\x12\x0e.user.UserData\x1a\x14.user.InsertResponseB6Z4ZServer/MicroServices/source/services/users;analyzerb\x06proto3"

var (
	file_analizer_proto_rawDescOnce sync.Once
	file_analizer_proto_rawDescData []byte
)

func file_analizer_proto_rawDescGZIP() []byte {
	file_analizer_proto_rawDescOnce.Do(func() {
		file_analizer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_analizer_proto_rawDesc), len(file_analizer_proto_rawDesc)))
	})
	return file_analizer_proto_rawDescData
}

var file_analizer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_analizer_proto_goTypes = []any{
	(*UserData)(nil),       // 0: user.UserData
	(*InsertResponse)(nil), // 1: user.InsertResponse
}
var file_analizer_proto_depIdxs = []int32{
	0, // 0: user.UserService.InsertUserData:input_type -> user.UserData
	1, // 1: user.UserService.InsertUserData:output_type -> user.InsertResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_analizer_proto_init() }
func file_analizer_proto_init() {
	if File_analizer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_analizer_proto_rawDesc), len(file_analizer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_analizer_proto_goTypes,
		DependencyIndexes: file_analizer_proto_depIdxs,
		MessageInfos:      file_analizer_proto_msgTypes,
	}.Build()
	File_analizer_proto = out.File
	file_analizer_proto_goTypes = nil
	file_analizer_proto_depIdxs = nil
}
