// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import (
	_ "embed"
	"log"

	"github.com/swaggo/swag"
)

//go:embed openapi.json
var embeddedDoc string

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:     "",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "",
	Description: "",
	// ... (el resto de tus campos de SwaggerInfo) ...
	
	InfoInstanceName: "swagger",
	SwaggerTemplate:  embeddedDoc, // 5. Asigna la variable aquí
	LeftDelim:        "{{",
	RightDelim:       "}}",
}



func init() {
	// Ahora el 'init' solo necesita registrar la variable
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
	log.Print("Documentación Swagger cargada desde archivo incrustado (embed).")
}